name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Run golangci-lint [linux]
      uses: golangci/golangci-lint-action@v3.1.0
      env:
        GOOS: "linux"

    - name: Run golangci-lint [windows]
      uses: golangci/golangci-lint-action@v3.1.0
      env:
        GOOS: "windows"

    - name: Build Docker Image
      run: docker build -t host-resolver:latest .

      # these set of tests need to run in docker since github action
      # ubuntu-latest VMs already have docker installed and ready to go
      # otherwise we would need to manipulate the /etc/resolv.conf
      # in the github actions machine which is not recommended
    - name: Run DNS test inside container
      run: docker run --dns 127.0.0.1 host-resolver:latest
